---
version: '2'
services:
  zookeeper-1:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kf-net
  kafka-1:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
    ports:
      - 29092:29092
    networks:
      - kf-net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #flink-master:
  #  image: bde2020/flink-master:1.14.5-hadoop3.2
  #  hostname: flink-master
  #  container_name: flink-master
  #  environment:
  #    - INIT_DAEMON_STEP=setup_flink
  #  ports:
  #    - "8080:8080"
  #    - "8081:8081"
  #flink-worker:
  #  image: bde2020/flink-worker:1.14.5-hadoop3.2
  #  hostname: flink-worker
  #  container_name: flink-worker
  #  environment:
  #    - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
    ##    - FLINK_NUM_TASK_SLOTS=2
  #  depends_on:
  #    - "flink-master"
networks:
  kf-net:
    driver: bridge